[package]
name = "bulk-convert"
version = "0.1.1"
authors = ["Alice Ryhl <alice@ryhl.io>"]
edition = "2021"

[profile.release]
panic = "abort"

[dependencies]

[target.'cfg(windows)'.dependencies]
which = "4.2.2"